-- use voyadb;
show tables;
insert into employee values ('Hi',4, 5000);
select * from employee where emp_id = 2;
Alter table employee add column city varchar(20) default 'Bangalore';
select * from employee;
alter table employee drop city;
desc employee;
select * from employee;
alter table employee add column city varchar(20);
insert into employee values('Am',5,6000);
update employee set city = 'Bangalore' where emp_id<3;
select * from employee;
Alter table employee add column department varchar(20) not null;
select * from employee;
Alter table employee modify column department varchar(20);
desc employee;
Alter table employee add column zip Integer;
desc employee;
Alter table employee CHANGE zip zipcode INTEGER;
DESC employee;
select * from employee order by emp_name;
select * from employee order by emp_name desc;
CREATE table student( stud_name varchar(20), student_id int, department varchar(20) );
desc student;
insert into student values ( 'Abdul', 1, 'Physics');
insert into student values ( 'Ajay', 2, 'Chemistry');
insert into student values ( 'Anil', 3, 'Maths');
insert into student values ( 'Ajay', 4, 'Bio');
insert into student values ( 'Akhil', 5, 'Physics');
insert into student values ( 'Bharghav', 6, 'Chemistry');
insert into student values ( 'Balaji', 7, 'Maths');
insert into student values ( 'Chandan', 8, 'Bio');
insert into student values ( 'Chethan', 9, 'Physics');
insert into student values ( 'Hitaishi', 10, 'Maths');
Alter table student add column city varchar(20);
update student set city= 'Bangalore' where student_id>5;
update student set city= 'Mumbai' where student_id<5;
Alter table student add column course varchar(20) not null default 'Java';
Alter table student add column mystate INTEGER;
Alter table student modify column mystate varchar(20);
Alter table student CHANGE mystate state varchar(20);
Alter table student add column zipcode integer;
update student set course = 'Angular' where student_id<3;
update student set course = 'Spring' where student_id>3;
select * from student order by stud_name;
delete from employee where emp_id=1;
select * from employee;
select * from student where stud_name LIKE 'a____';
select * from student where city IN('Bangalore','Pune');
select * from student where student_id between 1 and 5;
select stud_name as Student_Name, student_id as Stud_id,city as stud_city,department as Student_department;